---
version: '3'
services:
  go-web:
    build:
      context: .
      dockerfile: go.dockerfile
    command: ["tail -f /dev/null"]
    environment:
      - CONFIG_PATH=/workspaces/configs/server.json
      - PORT=8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/id_rsa:/home/willes/.ssh/id_rsa
      - ~/.kube/config:/home/willes/.kube/config
      - ..:/workspaces
    ports:
      - 8101:8000
