/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	workerv1 "github.com/willeslau/k8s-controller/pkg/apis/worker/v1"
	versioned "github.com/willeslau/k8s-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/willeslau/k8s-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/willeslau/k8s-controller/pkg/client/listers/worker/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WorkerInformer provides access to a shared informer and lister for
// Workers.
type WorkerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.WorkerLister
}

type workerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWorkerInformer constructs a new informer for Worker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWorkerInformer constructs a new informer for Worker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WillesxmV1().Workers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WillesxmV1().Workers(namespace).Watch(context.TODO(), options)
			},
		},
		&workerv1.Worker{},
		resyncPeriod,
		indexers,
	)
}

func (f *workerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&workerv1.Worker{}, f.defaultInformer)
}

func (f *workerInformer) Lister() v1.WorkerLister {
	return v1.NewWorkerLister(f.Informer().GetIndexer())
}
