apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: worker.willesxm.k8s.io
spec:
  group: willesxm.k8s.io
  version: v1
  names:
    kind: worker
    plural: foos
  scope: Namespaced
