apiVersion: willesxm.k8s.io/v1
kind: Worker
metadata:
  name: sample-worker
  labels:
    app: rpc-server
spec:
  project: test-project
  resources:
    concurrency: 10
    cpu: 1
    memory: 10
    gpu: false
  image: nginx
  # volumes:
  # - name: data
  #   persistentVolumeClaim: data
  # volumeMounts:
  # - volume: data
  #   mountPath: /home/data
  #   subpath: sample
