apiVersion: willesxm.k8s.io/v1
kind: Worker
metadata:
  name: worker
  labels:
    app: rpc-server-v2
spec:
  project: project
  replicas: 2
  resources:
    concurrency: 10
    cpu: 100m
    memory: 50M
    gpu: false
  image: nginx
  # volumes:
  # - name: data
  #   persistentVolumeClaim: data
  # volumeMounts:
  # - volume: data
  #   mountPath: /home/data
  #   subpath: sample
